### ISSUE TITLE
clean up double-dash values

### ISSUE THREAD

**Issue by mattbishop** [smrsan76/dashify-unicode#1]
I'm changing from dashify to this lib, but one thing dashify does is clean up double-dashes, like `this--has----many------dashes` -> `this-has-many-dashes`.

I think you need this at the end, just before lowerCase():
```
    // Remove double-dashes
    .replace(/-{2,}/g, '-')
```

**Comment by smrsan76** [comment]
Hi @mattbishop 

Thanks for taking care of this package and your contribution.

I've recently published the [v1.0.2 ](https://www.npmjs.com/package/dashify-unicode/v/1.0.2)package and I hope that it could solve your issue.

Feel free to reopen this issue, if the problem persists.
